global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'connect'
    static_configs:
      - targets: ['connect:8083']

  - job_name: 'kafdrop'
    static_configs:
      - targets: ['kafdrop:9000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
